-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Kargath Bladefist", {
	[-9396] = "cyan",
	[158986] = {"blue","red"},
	[159113] = {"blue","orange"},
	[159250] = "yellow",
	[159311] = "blue",
	[159413] = "blue",
	[159947] = {"blue","orange","yellow"},
	[160521] = "yellow",
	[162497] = {"blue","red"},
	["arena_sweeper"] = "orange",
})

BigWigs:AddSounds("Kargath Bladefist", {
	[158986] = "long",
	[159113] = "warning",
	[159311] = "info",
	[159413] = "info",
	[159947] = "alert",
	[160521] = "alarm",
	[162497] = "alarm",
	["arena_sweeper"] = "info",
})

BigWigs:AddColors("The Butcher", {
	[-10228] = "yellow",
	[156151] = {"blue","orange"},
	[156152] = "blue",
	[156157] = "yellow",
	[156197] = "orange",
	[163046] = "blue",
	["berserk"] = {"orange","red","yellow"},
	["frenzy"] = {"cyan","red"},
})

BigWigs:AddSounds("The Butcher", {
	[156151] = "warning",
	[156152] = "alarm",
	[156197] = "alert",
	[163046] = "alarm",
	["berserk"] = "alarm",
	["frenzy"] = "alarm",
})

BigWigs:AddColors("Tectus", {
	[162288] = "yellow",
	[162346] = {"blue","green"},
	[162475] = "green",
	[162518] = "red",
	[162892] = {"blue","orange"},
	[162894] = "orange",
	[162968] = {"blue","yellow"},
	[163312] = "orange",
	["adds"] = "yellow",
	["berserk"] = {"orange","red","yellow"},
})

BigWigs:AddSounds("Tectus", {
	[162346] = "alarm",
	[162475] = "long",
	[162518] = "warning",
	[162892] = "warning",
	[162894] = "alert",
	[162968] = {"alarm","alert"},
	["adds"] = "info",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Brackenspore", {
	[159219] = "orange",
	[159996] = "red",
	[160013] = "blue",
	[163241] = {"blue","yellow"},
	[163755] = "orange",
	[163794] = "orange",
	[164125] = "red",
	["berserk"] = {"orange","red","yellow"},
	["flesh_eater"] = "orange",
	["living_mushroom"] = "green",
	["mind_fungus"] = "yellow",
	["rejuvenating_mushroom"] = "green",
	["spore_shooter"] = "yellow",
})

BigWigs:AddSounds("Brackenspore", {
	[159219] = "warning",
	[159996] = "alarm",
	[160013] = "alert",
	[163241] = "warning",
	[163755] = "alarm",
	[164125] = "info",
	["berserk"] = "alarm",
	["flesh_eater"] = "long",
	["living_mushroom"] = "long",
	["mind_fungus"] = "long",
	["rejuvenating_mushroom"] = "info",
	["spore_shooter"] = "info",
})

BigWigs:AddColors("Twin Ogron", {
	[143834] = "orange",
	[157943] = "yellow",
	[158057] = "yellow",
	[158093] = "orange",
	[158134] = "orange",
	[158200] = "yellow",
	[158241] = "blue",
	[158385] = "orange",
	[158521] = "yellow",
	[163297] = {"blue","cyan"},
	[163372] = "cyan",
	[167200] = {"blue","cyan"},
	["berserk"] = {"orange","red","yellow"},
	["volatility_self"] = "blue",
})

BigWigs:AddSounds("Twin Ogron", {
	[157943] = "alert",
	[158057] = "alert",
	[158093] = "long",
	[158134] = "alarm",
	[158200] = "alert",
	[158241] = "info",
	[158385] = {"alarm","info"},
	["berserk"] = "alarm",
	["volatility_self"] = "warning",
})

BigWigs:AddColors("Ko'ragh", {
	[160734] = {"cyan","green"},
	[161242] = {"blue","green"},
	[161328] = {"blue","yellow"},
	[161612] = "green",
	[162184] = "yellow",
	[162185] = "red",
	[162186] = {"blue","orange"},
	[172747] = {"blue","cyan"},
	[172895] = {"blue","yellow"},
	["volatile_anomaly"] = "yellow",
})

BigWigs:AddSounds("Ko'ragh", {
	[160734] = {"info","long"},
	[161328] = "alarm",
	[161612] = "warning",
	[162184] = "alert",
	[162185] = "alarm",
	[162186] = "warning",
	[172747] = "alarm",
	[172895] = {"alert","info"},
	["volatile_anomaly"] = "info",
})

BigWigs:AddColors("Imperator Mar'gok", {
	[-9921] = "cyan",
	[156225] = {"blue","yellow"},
	[156238] = "orange",
	[156467] = "red",
	[156471] = "yellow",
	[157349] = "orange",
	[157763] = "blue",
	[157801] = {"blue","red","yellow"},
	[158553] = {"blue","yellow"},
	[158563] = "orange",
	[158605] = {"blue","orange"},
	[159515] = {"blue","yellow"},
	[165102] = {"blue","yellow"},
	[165116] = "green",
	[165243] = "yellow",
	[165595] = "blue",
	[165876] = "red",
	[176533] = "blue",
	[176537] = "blue",
	[178468] = "orange",
	[178607] = "orange",
	["adds"] = "yellow",
	["berserk"] = {"orange","red","yellow"},
	["stages"] = "cyan",
	["volatile_anomaly"] = "yellow",
})

BigWigs:AddSounds("Imperator Mar'gok", {
	[-9921] = "info",
	[156238] = "alert",
	[156467] = "warning",
	[156471] = "info",
	[157763] = "alarm",
	[157801] = "alert",
	[158553] = "alarm",
	[158563] = "warning",
	[158605] = "alarm",
	[159515] = "warning",
	[165102] = "alert",
	[165243] = "info",
	[165595] = "warning",
	[165876] = {"info","long"},
	[176533] = "info",
	[176537] = "alarm",
	[178468] = "alert",
	[178607] = "alarm",
	["adds"] = "info",
	["berserk"] = "alarm",
	["stages"] = {"info","long"},
	["volatile_anomaly"] = "info",
})

BigWigs:AddColors("Highmaul Trash", {
	[166200] = "blue",
	[172066] = "blue",
	[173827] = "blue",
	[174404] = "blue",
	[175636] = "blue",
	[175654] = "blue",
})

BigWigs:AddSounds("Highmaul Trash", {
	[166200] = "alarm",
	[172066] = "alarm",
	[173827] = "alert",
	[174404] = "alarm",
	[175636] = "alarm",
	[175654] = "alert",
})

BigWigs:AddColors("Beastlord Darmac", {
	[154960] = {"blue","orange","red"},
	[154975] = "yellow",
	[154981] = {"blue","orange"},
	[154989] = {"blue","orange"},
	[155030] = {"blue","yellow"},
	[155061] = {"blue","orange","yellow"},
	[155198] = "red",
	[155222] = "yellow",
	[155236] = {"blue","yellow"},
	[155247] = "yellow",
	[155321] = "yellow",
	[155499] = {"blue","orange"},
	[155657] = "blue",
	[156823] = "blue",
	[156824] = "blue",
	[159043] = {"blue","orange"},
	["berserk"] = {"orange","red","yellow"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("Beastlord Darmac", {
	[154960] = {"alarm","warning"},
	[154981] = "info",
	[154989] = "alert",
	[155030] = "warning",
	[155061] = "warning",
	[155198] = "alert",
	[155236] = "warning",
	[155499] = "alert",
	[155657] = "alarm",
	[156823] = "alarm",
	[156824] = "alarm",
	[159043] = "alarm",
	["berserk"] = "alarm",
	["stages"] = "info",
})

BigWigs:AddColors("Gruul", {
	[155078] = {"blue","yellow"},
	[155080] = "orange",
	[155301] = "yellow",
	[155326] = {"blue","orange"},
	[155539] = {"green","red"},
	[173192] = "blue",
	["berserk"] = {"orange","red","yellow"},
})

BigWigs:AddSounds("Gruul", {
	[155080] = "warning",
	[155301] = "info",
	[155326] = {"alarm","alert"},
	[155539] = {"info","long"},
	[173192] = "alarm",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Oregorger", {
	[155898] = "yellow",
	[156203] = {"blue","yellow"},
	[156240] = "red",
	[156390] = "orange",
	[156877] = "orange",
	[173471] = {"blue","yellow"},
	["berserk"] = "red",
	["stages"] = {"cyan","green"},
})

BigWigs:AddSounds("Oregorger", {
	[156203] = "alarm",
	[156240] = "warning",
	[156390] = "alarm",
	[156877] = "alert",
	[173471] = "warning",
	["berserk"] = {"alarm","info"},
	["stages"] = {"info","long"},
})

BigWigs:AddColors("Hans'gar and Franzok", {
	[153470] = "yellow",
	[155747] = {"blue","yellow"},
	[155818] = "blue",
	[156938] = {"blue","red"},
	[157139] = {"blue","yellow"},
	[160838] = "orange",
	[162124] = "cyan",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Hans'gar and Franzok", {
	[155747] = "alarm",
	[155818] = "alarm",
	[156938] = {"alarm","warning"},
	[160838] = "long",
	[162124] = "alert",
	["stages"] = "info",
})

BigWigs:AddColors("Flamebender Ka'graz", {
	[-9352] = "yellow",
	[154932] = {"blue","green"},
	[154950] = {"blue","yellow"},
	[154952] = "blue",
	[155064] = {"blue","green"},
	[155074] = {"blue","yellow"},
	[155277] = {"blue","yellow"},
	[155318] = {"blue","orange"},
	[155493] = {"cyan","red"},
	[155776] = "red",
	[156018] = "yellow",
	[156040] = "yellow",
	[163284] = {"blue","yellow"},
})

BigWigs:AddSounds("Flamebender Ka'graz", {
	[154932] = "warning",
	[154950] = "info",
	[154952] = "alarm",
	[155064] = "warning",
	[155074] = "warning",
	[155277] = "alert",
	[155318] = "alarm",
	[155493] = {"info","long"},
	[155776] = "alarm",
	[163284] = "warning",
})

BigWigs:AddColors("Operator Thogar", {
	[155864] = {"blue","yellow"},
	[155921] = {"blue","yellow"},
	[159481] = {"blue","yellow"},
	[160140] = {"blue","red"},
	[163753] = "orange",
	["trains"] = "cyan",
})

BigWigs:AddSounds("Operator Thogar", {
	[155864] = "alarm",
	[155921] = "warning",
	[159481] = "warning",
	[160140] = "alert",
	["trains"] = "long",
})

BigWigs:AddColors("Kromog", {
	[-9702] = "yellow",
	[156704] = "orange",
	[156766] = {"blue","yellow"},
	[156852] = "orange",
	[156861] = {"cyan","red"},
	[157054] = "red",
	[157060] = "green",
	[157592] = "orange",
	[158217] = "red",
	[173917] = "yellow",
	["berserk"] = {"orange","red","yellow"},
})

BigWigs:AddSounds("Kromog", {
	[156704] = "alarm",
	[156766] = "warning",
	[156861] = {"alarm","info"},
	[157060] = "info",
	[157592] = "alert",
	["berserk"] = "alarm",
})

BigWigs:AddColors("The Iron Maidens", {
	[155794] = {"blue","yellow"},
	[156109] = {"blue","orange"},
	[156601] = "red",
	[156631] = {"blue","orange"},
	[158010] = {"blue","orange"},
	[158315] = {"blue","yellow"},
	[158599] = "yellow",
	[158683] = "blue",
	[158692] = {"blue","orange"},
	[158708] = "orange",
	[159336] = {"cyan","red"},
	[159724] = {"blue","yellow"},
	[164271] = {"blue","red"},
	["bombardment"] = "cyan",
	["ship"] = "cyan",
})

BigWigs:AddSounds("The Iron Maidens", {
	[156109] = "info",
	[156631] = "alarm",
	[158010] = "alert",
	[158683] = "alarm",
	[158692] = "alert",
	[158708] = "alert",
	[159336] = "long",
	[159724] = "alert",
	[164271] = {"alarm","warning"},
	["ship"] = "info",
})

BigWigs:AddColors("The Blast Furnace", {
	[-10325] = "green",
	[-10324] = "blue",
	[155173] = {"blue","orange"},
	[155179] = "blue",
	[155186] = "orange",
	[155192] = "green",
	[155209] = "yellow",
	[155225] = "blue",
	[155242] = {"blue","yellow"},
	[156934] = {"blue","orange"},
	[156937] = "yellow",
	[163776] = "red",
	[174731] = {"green","red"},
	[175104] = {"blue","yellow"},
	[176121] = "blue",
	[176133] = "red",
	[176141] = "green",
	["berserk"] = {"orange","red","yellow"},
	["engineer"] = "yellow",
	["firecaller"] = "yellow",
	["guard"] = "yellow",
	["operator"] = "yellow",
	["stages"] = "cyan",
})

BigWigs:AddSounds("The Blast Furnace", {
	[-10325] = "info",
	[-10324] = "alarm",
	[155173] = "alert",
	[155179] = "alert",
	[155186] = "alert",
	[155192] = "alarm",
	[155225] = {"alarm","info"},
	[155242] = "warning",
	[156934] = {"alarm","info"},
	[163776] = "long",
	[174731] = "info",
	[176121] = "alarm",
	[176133] = "alarm",
	["berserk"] = "alarm",
	["engineer"] = "info",
	["firecaller"] = "info",
	["guard"] = "info",
	["operator"] = "info",
	["stages"] = "info",
})

BigWigs:AddColors("Blackhand", {
	[155992] = "orange",
	[156030] = "yellow",
	[156096] = {"blue","red","yellow"},
	[156401] = "blue",
	[156425] = "orange",
	[156653] = {"blue","yellow"},
	[156667] = "yellow",
	[156928] = "yellow",
	[157000] = {"blue","orange"},
	[158054] = "orange",
	[162585] = "red",
	[163008] = "orange",
	["siegemaker"] = "yellow",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Blackhand", {
	[155992] = "warning",
	[156030] = "long",
	[156096] = "alarm",
	[156401] = "info",
	[156425] = "alert",
	[156653] = "alert",
	[156667] = "info",
	[157000] = "alert",
	[158054] = "warning",
	[162585] = "alarm",
	[163008] = "alarm",
	["stages"] = "long",
})

BigWigs:AddColors("Blackrock Foundry Trash", {
	[18501] = {"blue","orange","yellow"},
	[159632] = {"blue","green"},
	[160260] = "blue",
	[162663] = "blue",
	[163121] = {"blue","orange","yellow"},
	[171613] = "orange",
	[174773] = "blue",
	[175583] = {"blue","green"},
	[175594] = {"blue","green","orange"},
	[175624] = {"blue","green","orange"},
	[175643] = "blue",
	[175765] = {"blue","orange"},
	[175993] = {"blue","red"},
	[177806] = "green",
})

BigWigs:AddSounds("Blackrock Foundry Trash", {
	[18501] = "warning",
	[159632] = "alarm",
	[160260] = "alert",
	[162663] = "alert",
	[163121] = "warning",
	[171613] = "warning",
	[174773] = "alert",
	[175583] = "alarm",
	[175594] = "warning",
	[175624] = "warning",
	[175643] = "alert",
	[175765] = "warning",
	[175993] = "warning",
})

BigWigs:AddColors("Hellfire Assault", {
	[180184] = "orange",
	[180945] = "orange",
	[181968] = "green",
	[184238] = "orange",
	[184243] = {"blue","orange"},
	[184369] = {"blue","yellow"},
	[184394] = "orange",
	[185021] = "yellow",
	[185806] = {"blue","yellow"},
	[185816] = "red",
	[188101] = "red",
	[190748] = {"blue","yellow"},
	["adds"] = "cyan",
	["siegevehicles"] = "cyan",
})

BigWigs:AddSounds("Hellfire Assault", {
	[180184] = "long",
	[180945] = "long",
	[184238] = "info",
	[184369] = "alarm",
	[184394] = "info",
	[185816] = "alert",
	[190748] = "info",
	["siegevehicles"] = "info",
})

BigWigs:AddColors("Iron Reaver", {
	[179889] = "red",
	[181999] = "red",
	[182001] = "blue",
	[182020] = "yellow",
	[182055] = "red",
	[182066] = "red",
	[182074] = "blue",
	[182280] = {"blue","orange"},
	[185282] = "yellow",
	["berserk"] = {"orange","red","yellow"},
})

BigWigs:AddSounds("Iron Reaver", {
	[179889] = "info",
	[181999] = "alarm",
	[182001] = "alarm",
	[182020] = "long",
	[182055] = "info",
	[182066] = "info",
	[182074] = "alarm",
	[182280] = "warning",
	[185282] = "long",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Kormrok", {
	[180244] = "orange",
	[181208] = "blue",
	[181292] = "yellow",
	[181296] = "orange",
	[181299] = "red",
	[181305] = "yellow",
	[181306] = {"blue","orange"},
	[181307] = {"blue","orange"},
	[185686] = "blue",
	[185687] = "blue",
	[186882] = "red",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Kormrok", {
	[180244] = "alert",
	[181208] = "alarm",
	[181292] = "long",
	[181296] = "info",
	[181305] = "warning",
	[181306] = "warning",
	[181307] = "warning",
	[185686] = "alarm",
	[185687] = "alarm",
	[186882] = "alarm",
	["stages"] = "info",
})

BigWigs:AddColors("Hellfire High Council", {
	[183885] = "yellow",
	[184355] = {"blue","yellow"},
	[184358] = {"blue","orange"},
	[184366] = "red",
	[184449] = "yellow",
	[184476] = {"blue","yellow"},
	[184657] = "red",
	[184681] = "orange",
	[184847] = {"blue","orange"},
	["berserk"] = {"orange","red","yellow"},
})

BigWigs:AddSounds("Hellfire High Council", {
	[184355] = {"alarm","alert"},
	[184358] = "warning",
	[184476] = {"alarm","info"},
	[184657] = "long",
	[184681] = "alert",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Kilrogg Deadeye", {
	[-11269] = "cyan",
	[-11266] = "cyan",
	[-11263] = "cyan",
	[-11261] = "cyan",
	[180033] = "yellow",
	[180163] = "yellow",
	[180199] = {"blue","red"},
	[180224] = "orange",
	[180618] = "yellow",
	[182428] = "green",
	[183917] = "orange",
	[187089] = {"blue","green"},
	[188852] = "blue",
	[188929] = {"blue","red"},
})

BigWigs:AddSounds("Kilrogg Deadeye", {
	[-11269] = "info",
	[-11266] = "info",
	[-11263] = "info",
	[-11261] = "info",
	[180199] = "warning",
	[180224] = "long",
	[182428] = "long",
	[183917] = "alert",
	[188852] = "alarm",
	[188929] = "alarm",
})

BigWigs:AddColors("Gorefiend", {
	[-11020] = "cyan",
	[179864] = {"blue","orange"},
	[179909] = {"blue","yellow"},
	[179977] = {"blue","red"},
	[179995] = "blue",
	[180148] = "blue",
	[181295] = {"orange","yellow"},
	[181582] = "red",
	[181973] = "green",
	[182601] = "blue",
	[185189] = {"blue","green"},
	[187814] = {"blue","red"},
})

BigWigs:AddSounds("Gorefiend", {
	[-11020] = {"info","warning"},
	[179864] = "alarm",
	[179909] = {"alert","warning"},
	[179977] = "alarm",
	[179995] = "alarm",
	[180148] = {"alarm","warning"},
	[181295] = {"alert","long"},
	[181582] = "alert",
	[181973] = "long",
	[182601] = "alarm",
	[185189] = "warning",
	[187814] = "alert",
})

BigWigs:AddColors("Shadow-Lord Iskar", {
	[179202] = "blue",
	[181753] = {"blue","red"},
	[181824] = {"blue","orange"},
	[181827] = "orange",
	[181912] = "red",
	[181956] = {"blue","yellow"},
	[182200] = {"blue","yellow"},
	[182323] = "orange",
	[182582] = "blue",
	[185345] = {"blue","red"},
	[185510] = {"blue","cyan","orange","yellow"},
	["berserk"] = {"orange","red","yellow"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("Shadow-Lord Iskar", {
	[179202] = {"info","warning"},
	[181753] = "alert",
	[181824] = "warning",
	[181827] = "alert",
	[181912] = "long",
	[181956] = {"alarm","warning"},
	[182200] = "alert",
	[182582] = {"alarm","alert"},
	[185345] = "long",
	[185510] = "info",
	["berserk"] = "alarm",
	["stages"] = "info",
})

BigWigs:AddColors("Socrethar the Eternal", {
	[-11778] = "yellow",
	[180008] = "orange",
	[180221] = {"blue","orange"},
	[181288] = "orange",
	[182038] = {"blue","yellow"},
	[182051] = {"blue","orange"},
	[182218] = "blue",
	[182392] = "yellow",
	[182769] = "blue",
	[183329] = "red",
	[183331] = "yellow",
	[184124] = {"blue","yellow"},
	[188692] = "orange",
	[188693] = "red",
	["berserk"] = {"orange","red","yellow"},
	["dominator"] = "cyan",
	["portals"] = "cyan",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Socrethar the Eternal", {
	[180008] = "info",
	[180221] = "alarm",
	[181288] = "alarm",
	[182038] = "alarm",
	[182051] = "alarm",
	[182218] = "alarm",
	[182392] = "alert",
	[182769] = "alarm",
	[183329] = "long",
	[183331] = "alert",
	[184124] = "alarm",
	[188692] = "info",
	[188693] = "alert",
	["berserk"] = "alarm",
	["dominator"] = "warning",
	["portals"] = "info",
	["stages"] = "long",
})

BigWigs:AddColors("Fel Lord Zakuun", {
	[179406] = "yellow",
	[179407] = {"blue","red"},
	[179583] = "orange",
	[179620] = "blue",
	[179711] = {"blue","yellow"},
	[181508] = {"blue","green","yellow"},
	[189009] = "orange",
	["stages"] = {"cyan","red"},
})

BigWigs:AddSounds("Fel Lord Zakuun", {
	[179407] = "warning",
	[179583] = "info",
	[179620] = "alarm",
	[179711] = {"alert","info"},
	[181508] = "alarm",
	[189009] = "alarm",
	["stages"] = "long",
})

BigWigs:AddColors("Xhul'horac", {
	[186063] = "blue",
	[186073] = "blue",
	[186134] = "blue",
	[186135] = "blue",
	[186333] = {"blue","yellow"},
	[186407] = {"blue","yellow"},
	[186453] = {"blue","red"},
	[186490] = {"blue","orange"},
	[186546] = "orange",
	[186783] = {"blue","red"},
	[187204] = {"blue","red"},
	[190223] = {"blue","orange","yellow"},
	[190224] = {"blue","orange","yellow"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("Xhul'horac", {
	[186134] = "long",
	[186135] = "long",
	[186333] = "alarm",
	[186407] = "alarm",
	[186490] = {"alarm","alert"},
	[186546] = "alert",
	[190223] = {"long","warning"},
	[190224] = {"long","warning"},
	["stages"] = "info",
})

BigWigs:AddColors("Tyrant Velhari", {
	[-11170] = "cyan",
	[-11163] = "cyan",
	[-11155] = "cyan",
	[180000] = {"blue","orange"},
	[180004] = "yellow",
	[180025] = {"blue","yellow"},
	[180040] = {"green","orange"},
	[180260] = {"blue","yellow"},
	[180300] = "red",
	[180526] = {"blue","red"},
	[180600] = {"blue","yellow"},
	[180608] = "red",
	[182459] = {"blue","red"},
	[185237] = {"blue","orange"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("Tyrant Velhari", {
	[180000] = "warning",
	[180025] = "alert",
	[180040] = "long",
	[180260] = "info",
	[180300] = "long",
	[180526] = "alarm",
	[180600] = {"alarm","info"},
	[180608] = "alert",
	[182459] = "warning",
})

BigWigs:AddColors("Mannoroth", {
	[181099] = {"blue","yellow"},
	[181119] = {"blue","orange"},
	[181126] = "green",
	[181275] = {"blue","red","yellow"},
	[181354] = "orange",
	[181359] = {"blue","orange"},
	[181557] = "yellow",
	[181597] = {"blue","yellow"},
	[181735] = "green",
	[181799] = "red",
	[186362] = {"blue","yellow"},
	[190070] = "blue",
	[190482] = "blue",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Mannoroth", {
	[181099] = {"alarm","info"},
	[181275] = {"alarm","warning"},
	[181354] = "warning",
	[181597] = {"alarm","info"},
	[181735] = "alert",
	[181799] = "long",
	[186362] = "alarm",
	[190070] = "alert",
	[190482] = "long",
	["stages"] = "info",
})

BigWigs:AddColors("Archimonde", {
	[182225] = "orange",
	[182826] = {"blue","red"},
	[183254] = "orange",
	[183817] = {"blue","orange"},
	[183828] = {"blue","yellow"},
	[183864] = {"blue","yellow"},
	[183865] = {"blue","yellow"},
	[183963] = "blue",
	[184964] = {"blue","cyan","yellow"},
	[185590] = "yellow",
	[186123] = {"blue","green","red"},
	[186961] = {"blue","orange"},
	[187050] = {"blue","yellow"},
	[187180] = "yellow",
	[187255] = "blue",
	[189894] = "blue",
	[190050] = "yellow",
	[190394] = "green",
	[190506] = "orange",
	[190703] = "yellow",
	[190821] = "yellow",
	["overfiend"] = "green",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Archimonde", {
	[182225] = "alert",
	[182826] = "alarm",
	[183254] = "alert",
	[183817] = "warning",
	[183828] = "warning",
	[183865] = "alert",
	[183963] = "info",
	[184964] = {"alarm","info"},
	[185590] = "alarm",
	[186123] = {"alarm","info"},
	[186961] = "warning",
	[187050] = "alarm",
	[187180] = {"info","warning"},
	[187255] = "info",
	[189894] = "alarm",
	[190050] = "long",
	[190394] = "alert",
	[190506] = "alert",
	[190703] = "alarm",
	[190821] = "alarm",
	["overfiend"] = "alert",
	["stages"] = {"info","long"},
})

BigWigs:AddColors("Hellfire Citadel Trash", {
	[179219] = {"blue","yellow"},
	[182644] = {"blue","orange"},
	[184587] = "blue",
	[184621] = "blue",
	[184986] = {"blue","yellow"},
	[186130] = {"blue","red"},
	[186197] = {"blue","yellow"},
	[187110] = {"blue","yellow"},
	[188072] = "blue",
	[188448] = "blue",
	[188476] = {"blue","orange"},
	[188510] = {"blue","yellow"},
	[189464] = "yellow",
	[189470] = "orange",
	[189491] = "green",
	[189512] = {"blue","red"},
	[189533] = {"blue","orange"},
	[189538] = {"blue","orange","yellow"},
	[189550] = "blue",
	[189595] = "orange",
	[189612] = "orange",
	[190043] = {"blue","orange"},
})

BigWigs:AddSounds("Hellfire Citadel Trash", {
	[179219] = "alarm",
	[182644] = "long",
	[184587] = "alarm",
	[184621] = "info",
	[186130] = "warning",
	[186197] = "warning",
	[187110] = "alarm",
	[188072] = "alarm",
	[188448] = "alarm",
	[188476] = "warning",
	[188510] = "alarm",
	[189464] = "warning",
	[189470] = "info",
	[189491] = "long",
	[189512] = "alarm",
	[189533] = "warning",
	[189538] = {"alarm","long"},
	[189550] = "alert",
	[189595] = "warning",
	[189612] = "info",
})

BigWigs:AddColors("Drov the Ruiner", {
	[175791] = "red",
	[175827] = "yellow",
	[175915] = "blue",
})

BigWigs:AddSounds("Drov the Ruiner", {
	[175791] = "alarm",
	[175915] = "alarm",
})

BigWigs:AddColors("Tarlna the Ageless", {
	[175973] = "red",
	[175979] = "yellow",
	[176001] = "blue",
	[176013] = "orange",
	[176037] = "blue",
})

BigWigs:AddSounds("Tarlna the Ageless", {
	[175973] = "alarm",
	[175979] = "long",
	[176001] = "alert",
	[176037] = "alert",
})

BigWigs:AddColors("Rukhmar", {
	[167615] = {"blue","yellow"},
	[167647] = "yellow",
	[167679] = "orange",
	[167757] = "blue",
})

BigWigs:AddSounds("Rukhmar", {
	[167615] = "warning",
	[167647] = "long",
	[167757] = "alarm",
})

BigWigs:AddColors("Supreme Lord Kazzak", {
	[187471] = {"blue","yellow"},
	[187664] = {"blue","orange"},
	[187668] = "blue",
	[187702] = "red",
})

BigWigs:AddSounds("Supreme Lord Kazzak", {
	[187471] = "info",
	[187664] = "alert",
	[187668] = "alarm",
	[187702] = "long",
})
