sudo: false

language: c

addons:
  apt:
    packages:
    - luarocks

env:
  global:
  - secure: "dtWxHFjlgXZue99tMzjj/JONTPQXYUcptrm/Cgbw2HRVkKSGE2LN7BpJJ9uu8oOQ1NHgaRmbrzW2Tx4tSqenCrLD/+1IWnB4SELGGlrix839ydiitoly6NT6OWZTGWUIw1TxWAHDxqjwXfiNZG5SMjgbKgOt4B63jPIB85UTInO3nXlBTU8Q5ieG3mPDVmu/wCnRbcLmrsWivWvHTiYpoFfRNO5CbZpyoMjyh47nOJ5sgwLqa81TSfqs5ahIVzz5nz4hzKjRPXfRPdcAOR9ZSc0k4aDpu08eDvm4hlXKLU7O+nIrc/cg8qMlFy34VKt49te99z3qd5DvzedlW8SvE9MgXjZIdermDQp8DRxyKTm9ARkI2vDsHl4lxScNeD4dMUwCG/1PM6Sw5IQoBm58L1PiNTLI70jMj3vEBC/Tl4DvRzljieOFOrndWGLxmintMJ0a5PebpuFWCYdBJyRe/v9KHL4AgNcV878FW1Zo824VBkhDSyKTzLUpAqG/EmmMGco5YGhYrVS8tyOuU9JYm21xgjgIrE1qI5CGMsTkl01SvKR9d67iG+ZT07UsZncrhvnoMN67RJp48tkqiOHg7K+eKJxHHHa7SNolCKTbzrGQSqtQpWYsueFcrlgwIWnxfj3vy0hHMFmbjjjUA9hfUe41ldkVetLCIu6maUZEuqs="
  - secure: "MMC2um5CdKldRx8a11kokYpXheSnP1JNAsAxnIobDttRL3ZvIM+k5D6R4gHa9JF84HRSvpt2L70xddE57crC34Lt8TpOKtw/erJkliZ5H0Klqku8cvieyGm+Iiucw8UI5BzhDtTM+a1sw4InHi//xAJnh/x+2z/4Ra77DyJ+hIfY83ygJEndDjE4SaaSVjbKTWfPV/WuOTpCD6tyQPBnMy23NReSQn5RenK+MPjLU9F9nfyKSa0hGGKwyWuBNrYBFbEybr5j2Jmkjr40FXl+xrUQYQrt0TkoPQh+qK7TcRRMInvmRAh3kci1yIctTCzuoBiKN1sfRztAjz5jim3WgYo0wRbe9et+Tt3Ac9AMM1NerksN0mxPPVjcupnjd2G39RweX8cpTc7ETvqItHNXZy1RPAzFFiStKBaWxY/2ABXbnf9+fa8mTzEQOYrnXsjysr43BoP7C0REmI2z9eZlPnv5aq0khmOKl0EZ4BEWbVKqaJUdkLqcW96LtcKWAuGPMXJuFnqlLei5LJHPRTN0TxI8znsFoyuN1938lgB2pj9GStFyArKadjiwLeAH2bOH6iimX+haMj2l4A62KlctvZmTkDyT9yS+K0UvXUl2boITd1f3Of5cdLEJDkeI/M9lTOWmfpBuh0tngA7fj+nDdpusehxm995UPFjMAIpi0vw="
  - secure: "COxm/EcUL1CsBGG/zTcq2t6RCkkqcPZsDZIGiZ9HGMuNK7h0b+zWZVAa5vsK5YHfctr6WnJn1PdgnZHvT+335doqXD7yKewUXEboa2SmqPKgNSdFfRkjRcvISFsoBrelyZ7WvoPJkufwWr1LJFFqP8+kMEDlIFJ4MuP+gGta3k/zaDc8CwRxb/Udw61wB5zmQ0R/H9XvFlYnecVye38v/twt7GlzWiyhTId4Vmjm5+LiYLsQejq2A9slvO8AGu7ZE5amJfXw7JPqO/uVxJV/Id4qLb52MveS7eHB3ENi4e8JR+9O4GV8JD+oittjrwO5QBVomJws9jW2qD0+8vE9HstZZNOwrCYKq+oTz2boBOSZnTwVorv0c80Mk9u78A/yjTHfYe7kgILBvRrcrqDVWsE1CDn66KepxYooCEK5k6esVAa0dL1IuodumF0HDgRBszT5Ac+eNK9H/kWW8RJsKMx6Bg2n0rF4phOFkHtjiNLCO7+n0EeKZW/+n94fhofIg3AQul3rIWK6VIwwggxbwn9QFD62G+HNCO9jzHUYLQ8P3zCAre9kiQu7BVr80Dl4LbTeEiu2wwkuf+qJQ62W1BFdF6FwJXgjORbb5OQs7mJGwr6EEAS1AogS+KTRIZ28qlKd+CTQhWCMKDeg/ZcFXjb72GxOkzFuC7LqKP4ScN8="

before_install: luarocks install --local luacheck

before_script: /home/travis/.luarocks/bin/luacheck . --no-color -qo "011"
script: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash

notifications:
  email:
    on_success: never
    on_failure: always
